
# install latest topcat
#RUN wget --quiet http://www.star.bris.ac.uk/~mbt/stilts/stilts.jar -O /usr/local/bin/stilts.jar \
#    && wget --quiet http://www.star.bris.ac.uk/~mbt/stilts/stilts -O /usr/local/bin/stilts \
#    && chmod +x /usr/local/bin/stilts

# install topcat with parquet
#RUN wget --quiet http://www.star.bris.ac.uk/~mbt/topcat/topcat-extra.jar -O /usr/local/bin/topcat-extra.jar \
#    && wget --quiet http://www.star.bris.ac.uk/~mbt/topcat/topcat -O /usr/local/bin/topcat \
#    && sed -i -e 's/topcat-full/topcat-extra/g' /usr/local/bin/topcat \
#    && chmod +x /usr/local/bin/topcat

# hack as topcat url is down (march 2023)
RUN wget -q https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/files/vault/sfabbro/topcat.tar.gz -O /topcat.tar.gz \
    && tar xf /topcat.tar.gz \
    && rm /topcat.tar.gz
