RUN mamba install cython=0.29* -y \
    && pip install --no-cache \
       gvar==11.11.* \
       lsqfit \
       fpdf

RUN git clone https://github.com/thomasorb/orb.git \
    && git clone https://github.com/thomasorb/orcs.git

RUN cd orb \
    && python setup.py build_ext --inplace \
    && python setup.py install \
    && cd .. \
    && cd orcs \
    && python setup.py install \
    && cd .. \
    && rm -rf orb orcs
